# Generated by Django 4.2.26 on 2025-12-04 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('toaki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendedorCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.CharField(choices=[('COMIDA', 'Comida'), ('VESTUARIO', 'Vestuário'), ('ACESSORIOS', 'Acessórios'), ('BEBIDAS', 'Bebidas'), ('SORVETES', 'Sorvetes'), ('OUTROS', 'Outros')], max_length=20)),
                ('perfil_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='toaki_app.perfilvendedor')),
            ],
            options={
                'verbose_name': 'Categoria do Vendedor',
                'verbose_name_plural': 'Categorias dos Vendedores',
                'db_table': 'vendedores_categorias',
                'unique_together': {('perfil_vendedor', 'categoria')},
            },
        ),
    ]
