# Generated by Django 4.2.26 on 2025-11-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toaki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='perfilvendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Base Usuarios'},
        ),
    ]
